name: Publish Prepatch

on:
  push:
    branches:
      - dev

env:
  NPM_TOKEN: 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

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
            credentials_json: '${{ secrets.ZEAGENT_DEV_SA }}'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set up npm token
        run: echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" > ~/.npmrc

      - name: Run Lerna Publish Prepatch
        run: npx lerna publish prepatch --yes